name: calculon 
channels:
  - defaults
dependencies:
  - python=3.7
  - pydot
  - graphviz
  - python-graphviz
  - pyyaml
  - pandas
  - plotly
  - psutil
  - conda-forge::python-kaleido
  - conda-forge::toposort
  - scipy
  - matplotlib
  - numpy
  - pyhdx
